### ISSUE TITLE
Migrate tests to typescript and test permit functions

### ISSUE THREAD

**Issue by albertocuestacanada** [wETH-v2/wETH-v2#10]
Just copy [this](https://github.com/albertocuestacanada/ERC20Permit/blob/master/utils/signatures.ts) and [this](https://github.com/albertocuestacanada/ERC20Permit/blob/master/test/erc20_permit.ts).

**Comment by dmihal** [comment]
Maybe [eth-permit](https://www.npmjs.com/package/eth-permit)? 😃

**Comment by Ro5s** [comment]
should we take advantage of mapping to track nonces? see: https://github.com/ethereum/EIPs/issues/3010#issuecomment-706444635

**Comment by albertocuestacanada** [comment]
`permit` tested with `eth-permit`, I don't see a reason to push for typescript.

**Comment by albertocuestacanada** [comment]
Re: tracking nonces with a mapping. It isn't a mature pattern yet, let's leave that for WETH11. Also, increased gas costs.
