### ISSUE TITLE
Flash minting

### ISSUE THREAD

**Issue by albertocuestacanada** [wETH-v2/wETH-v2#16]
I would consider allowing flash minting of weth.

**Comment by abcoathup** [comment]
Would be great to have Flash Minting.  (I was going to create an issue but @albertocuestacanada beat me to it).

https://blog.openzeppelin.com/flash-mintable-asset-backed-tokens/

**Comment by albertocuestacanada** [comment]
I can implement this on Tuesday night, if no one beats me to it.

**Comment by Ro5s** [comment]
nice @abcoathup just saw that OZ team deployed a FlashWETH :zap: on Ethereum while back~~~https://etherscan.io/address/0xf7705C1413CffCE6CfC0fcEfe3F3A12F38CB29dA#code

**Comment by albertocuestacanada** [comment]
I prefer to `lock` the functions that deal with Eth, restricting the feature to flash mint only Weth.

That's a discussion to be had though. Should we just `assert` that after the burn we still have all the ETH?
