### ISSUE TITLE
This would actually be WETH10, not WETH2

### ISSUE THREAD

**Issue by albertocuestacanada** [wETH-v2/wETH-v2#2]
Check here: https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code

**Comment by Ro5s** [comment]
Agreed. It feels important to stay in ‘canonical’ order. Lindy effect ftw! Wdyt @Agusx1211 ?

**Comment by albertocuestacanada** [comment]
@Ro5s, would you please DM me on Twitter?

**Comment by Ro5s** [comment]
sure thing 🤙

**Comment by Ro5s** [comment]
closed per https://github.com/wETH-v2/wETH-v2/pull/8
