### ISSUE TITLE
Use immutable variables where possible

### ISSUE THREAD

**Issue by albertocuestacanada** [wETH-v2/wETH-v2#6]
name, symbol, decimals, DOMAIN_SEPARATOR and PERMIT_TYPEHASH

**Comment by Ro5s** [comment]
Makes sense. Would it also be better to bump compiler up? I’ll defer to your judgment, as I saw you used these more advanced descriptions in ERC20Permit @albertocuestacanada

**Comment by Ro5s** [comment]
Some related jots: https://twitter.com/nanexcool/status/1314649151515299840?s=21

**Comment by Ro5s** [comment]
aiming to address here: https://github.com/wETH-v2/wETH-v2/pull/11 🏹

**Comment by Ro5s** [comment]
closed 📖 per https://github.com/wETH-v2/wETH-v2/pull/11
