### ISSUE TITLE
Use uint256 when possible

### ISSUE THREAD

**Issue by nanexcool** [wETH-v2/wETH-v2#7]
Especially when calculating keccak256:

`EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)`

and

`Permit(address src,address guy,uint256 wad,uint256 nonce,uint256 deadline)`

**Comment by Ro5s** [comment]
good idea. similarly, I am lo key debating whether to maintain the unique syntax of wETH (`wad` etc.), largely borrowed from DAI. It feels appropriate to bring syntax in line with OpenZeppelin and otherwise?

**Comment by Ro5s** [comment]
aiming to address here: https://github.com/wETH-v2/wETH-v2/pull/11 🏹

**Comment by Ro5s** [comment]
closed 📖 per https://github.com/wETH-v2/wETH-v2/pull/11
